export { DB, db } from "./storage/index.js";

export {
  camelToSnake,
  snakeToCamel,
  toIsoIfNeeded,
  normalizeTimestamps,
  encodeRecord,
  decodeRecord,
  decodeRows,
  getPrimaryKey,
  getPrimaryColumn,
  reportSupabaseError,
  reportSupabaseException,
  isDuplicatePrimaryError,
  getNextId,
  applyNullableFilter,
  insertRecord,
  updateByPrimary,
  deleteByPrimary,
  selectAll,
  selectSingle,
  clearTable,
  withTimestamp,
  DAY_MS,
  PEGAS_TURNOS,
  TABLE_PRIMARY_KEYS,
  TABLES_TO_RESET,
} from "./storage/core.js";
